const Projects = [
  {
    title: "Uxbridge Project 2024 COMPLETION - LONDON - NEW BUILD - 20 APARTMENTS & 3 RETAIL UNITS",
    slug: "uxbridge-project-2024-completion",
    description:
      "High-spec apartments with integrated retail space, finished to modern luxury standards. Situated in the heart of Uxbridge.",
    images: [
      "../Images/projects/Uxbridge Project/ux.jpg",
      "../Images/projects/Uxbridge Project/ux1.jpg",
      "../Images/projects/Uxbridge Project/ux2.jpg",
      "../Images/projects/Uxbridge Project/ux3.jpg",
      "../Images/projects/Uxbridge Project/ux4.jpg",
      "../Images/projects/Uxbridge Project/ux7.jpg",
      "../Images/projects/Uxbridge Project/ux8.jpg",
      "../Images/projects/Uxbridge Project/ux9.jpg",
      "../Images/projects/Uxbridge Project/ux10.jpg",
      "../Images/projects/Uxbridge Project/ux11.jpg",
      "../Images/projects/Uxbridge Project/ux12.jpg",
      "../Images/projects/Uxbridge Project/ux13.jpg",
      "../Images/projects/Uxbridge Project/ux14.jpg",
      "../Images/projects/Uxbridge Project/ux17.jpg",
      "../Images/projects/Uxbridge Project/ux18.jpg",
      "../Images/projects/Uxbridge Project/ux19.jpg",
    ],
    category: "Private Development",
  },
  {
    title: "hereford House Project 2024 COMPLETION - LONDON - NEW BUILD - 33 APARTMENTS & 3 RETAIL UNITS",
    slug: "hereford-project-2024-completion",
    description:
      "High-spec apartments with integrated retail space, finished to modern luxury standards. Situated in the heart of Uxbridge.",
    images: [
      "../Images/projects/Hereford House - London/hereford.JPG",
      "../Images/projects/Hereford House - London/hereford1.JPG",
      "../Images/projects/Hereford House - London/hereford2.JPG",
      "../Images/projects/Hereford House - London/hereford3.JPG",
      "../Images/projects/Hereford House - London/hereford4.JPG",
      "../Images/projects/Hereford House - London/hereford5.JPG",
      "../Images/projects/Hereford House - London/hereford6.JPG",
      "../Images/projects/Hereford House - London/hereford7.JPG",
      "../Images/projects/Hereford House - London/hereford8.JPG",
      "../Images/projects/Hereford House - London/hereford9.JPG",
      "../Images/projects/Hereford House - London/hereford10.JPG",
    ],
    category: "Private Development",
  },
  {
    title: "29 Shaa Road - Acton W3 - NEW BUILD - 19 APARTMENTS",
    slug: "sr29-project-2021-completion",
    description:
      "Boutique apartments with urban finishes, open-plan layouts, and eco-conscious features located in Hackney.",
    images: [
      "../Images/projects/29 shaa road/sr.jpg",
      "../Images/projects/29 shaa road/sr1.jpg",
      "../Images/projects/29 shaa road/sr2.jpg",
      "../Images/projects/29 shaa road/sr3.jpg",
      "../Images/projects/29 shaa road/sr4.jpg",
      "../Images/projects/29 shaa road/sr7.jpg",
      "../Images/projects/29 shaa road/sr8.jpg",
      "../Images/projects/29 shaa road/sr9.jpg",
      "../Images/projects/29 shaa road/sr10.jpg",
      "../Images/projects/29 shaa road/sr11.jpg",
    ],
    category: "Residential",
  },
  {
    title: "27 Shaa Road - Acton W3 - NEW BUILD - 9 APARTMENTS",
    slug: "sr27-project-2021-completion",
    description:
      "Boutique apartments with urban finishes, open-plan layouts, and eco-conscious features located in Hackney.",
    images: [
      "../Images/projects/27 Shaa Road - Acton W3/shaa.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa1.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa2.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa3.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa4.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa5.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa6.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa7.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa8.JPG",
    ],
    category: "Residential",
  },
  {
    title: "HACKNEY Project 2024 completion - NEW BUILD - 7 APARTMENTS",
    slug: "hackney-project-2020-completion",
    description:
      "Newly completed residential development featuring 10 contemporary apartments in the Hackney district.",
    images: [
      "../Images/projects/Hackney Project/hackney.JPG",
      "../Images/projects/Hackney Project/hackney1.JPG",
      "../Images/projects/Hackney Project/hackney2.JPG",
      "../Images/projects/Hackney Project/hackney3.JPG",
      "../Images/projects/Hackney Project/hackney4.JPG",
      "../Images/projects/Hackney Project/hackney5.JPG",
      "../Images/projects/Hackney Project/hackney7.JPG",
      "../Images/projects/Hackney Project/hackney8.JPG",
      "../Images/projects/Hackney Project/hackney9.JPG",
      "../Images/projects/Hackney Project/hackney10.JPG",
      "../Images/projects/Hackney Project/hackney11.JPG",
      "../Images/projects/Hackney Project/hackney12.JPG",
      "../Images/projects/Hackney Project/hackney13.JPG",
      "../Images/projects/Hackney Project/hackney14.PNG",
    ],
    category: "Residential",
  },
  {
    title: "BRISTOL Project 2024 completion - NEW BUILD - 9 APARTMENTS",
    slug: "bristol-project-2020-completion",
    description:
      "Newly completed residential development featuring 10 contemporary apartments in the Hackney district.",
    images: [
      "../Images/projects/Construction/con11.jpg",
      "../Images/projects/Construction/con1.JPG",
      "../Images/projects/Construction/con2.JPG",
      "../Images/projects/Construction/con3.JPG",
      "../Images/projects/Construction/con4.JPG",
      "../Images/projects/Construction/con5.JPG",
      "../Images/projects/Construction/con6.JPG",
      "../Images/projects/Construction/con7.JPG",
      "../Images/projects/Construction/con8.JPG",
      "../Images/projects/Construction/con9.JPG",
      "../Images/projects/Construction/con10.JPG",
      "../Images/projects/Construction/con12.jpg",
      "../Images/projects/Construction/con13.jpg",
    ],
    category: "Private Development",
  },
  {
    title: "2c shaa road Project 2020 completion - NEW BUILD - 10 APARTMENTS",
    slug: "sr2c-project-2020-completion",
    description:
      "Newly completed residential development featuring 10 contemporary apartments in the Hackney district.",
    images: [
      "../Images/projects/2c shaa road/2c11.png",
      "../Images/projects/2c shaa road/2c.jpg",
      "../Images/projects/2c shaa road/2c2.jpg",
      "../Images/projects/2c shaa road/2c3.jpg",
      "../Images/projects/2c shaa road/2c4.jpg",
      "../Images/projects/2c shaa road/2c7.jpg",
      "../Images/projects/2c shaa road/2c8.jpg",
      "../Images/projects/2c shaa road/2c9.jpg",
      "../Images/projects/2c shaa road/2c10.jpg",
      "../Images/projects/2c shaa road/2c1.jpg",
      "../Images/projects/2c shaa road/2c.jpg",
    ],
    category: "Private Development",
  },
  {
    title: "Chalrles Street - London Mayfar Project 2024 completion - NEW BUILD - 12 APARTMENTS",
    slug: "charles-project-2024-completion",
    description:
      "Newly completed residential development featuring 10 contemporary apartments in the Hackney district.",
    images: [
      "../Images/projects/Chalrles Street - London Mayfar/cs.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs1.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs2.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs3.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs4.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs5.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs6.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs7.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs8.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs9.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs10.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs11.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs12.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs13.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs14.jpg",
    ],
    category: "Residential",
  },
];

export default Projects;
