const Projects = [
  {
    title: "Paramount House, Uxbridge – Mixed-Use Development with 33 Apartments & 3 Retail Units",
    slug: "uxbridge-project-2024-completion",
    description:
      "Design and construction of a new-build mixed-use development comprising 33 residential apartments and 3  retail units. The project included full site clearance, enabling works, and steel frame. Residential units were completed to high specification with open-plan layouts, integrated kitchens, LVT flooring, and modern bathrooms.",
    images: [
      "../Images/projects/Uxbridge Project/ux.jpg",
      "../Images/projects/Uxbridge Project/ux1.jpg",
      "../Images/projects/Uxbridge Project/ux2.jpg",
      "../Images/projects/Uxbridge Project/ux3.jpg",
      "../Images/projects/Uxbridge Project/ux4.jpg",
      "../Images/projects/Uxbridge Project/ux7.jpg",
      "../Images/projects/Uxbridge Project/ux8.jpg",
      "../Images/projects/Uxbridge Project/ux9.jpg",
      "../Images/projects/Uxbridge Project/ux10.jpg",
      "../Images/projects/Uxbridge Project/ux11.jpg",
      "../Images/projects/Uxbridge Project/ux12.jpg",
      "../Images/projects/Uxbridge Project/ux13.jpg",
      "../Images/projects/Uxbridge Project/ux14.jpg",
      "../Images/projects/Uxbridge Project/ux17.jpg",
      "../Images/projects/Uxbridge Project/ux18.jpg",
      "../Images/projects/Uxbridge Project/ux19.jpg",
    ],
    category: "Private Development",
  },
  {
    title: "Hereford House, Mayfair – High-End Flat Reconfiguration with Smart Home Integration",
    slug: "hereford-project-2024-completion",
    description:
      "Complete modernisation and internal refurbishment of a luxury residence. The scope of works included full reconfiguration of internal layouts to optimise space and function, installation of bespoke Italian kitchen and bathroom fittings, smart home automation, and complete rewiring and replumbing. All works were delivered with a focus on minimal disruption to neighbouring flats. ",
    images: [
      "../Images/projects/Hereford House - London/hereford.JPG",
      "../Images/projects/Hereford House - London/hereford1.JPG",
      "../Images/projects/Hereford House - London/hereford2.JPG",
      "../Images/projects/Hereford House - London/hereford3.JPG",
      "../Images/projects/Hereford House - London/hereford4.JPG",
      "../Images/projects/Hereford House - London/hereford5.JPG",
      "../Images/projects/Hereford House - London/hereford6.JPG",
      "../Images/projects/Hereford House - London/hereford7.JPG",
      "../Images/projects/Hereford House - London/hereford8.JPG",
      "../Images/projects/Hereford House - London/hereford9.JPG",
      "../Images/projects/Hereford House - London/hereford10.JPG",
    ],
    category: "Private Development",
  },
  {
    title: "Shaa Road, Acton (Plot 1) – Full New-Build Residential House with Turnkey Finish",
    slug: "sr29-project-2021-completion",
    description:
      "Complete construction of a new-build residential house from groundworks through to final interior finishes. Works included piling and reinforced concrete foundations, structural brickwork, roof construction, full MEP (mechanical, electrical, and plumbing) installation, insulation, glazing, floor screeding, plastering, tiling, and interior decorating. Landscaping and driveway works were also completed to provide a full turnkey finish.",
    images: [
      "../Images/projects/29 shaa road/sr.jpg",
      "../Images/projects/29 shaa road/sr1.jpg",
      "../Images/projects/29 shaa road/sr2.jpg",
      "../Images/projects/29 shaa road/sr3.jpg",
      "../Images/projects/29 shaa road/sr4.jpg",
      "../Images/projects/29 shaa road/sr7.jpg",
      "../Images/projects/29 shaa road/sr8.jpg",
      "../Images/projects/29 shaa road/sr9.jpg",
      "../Images/projects/29 shaa road/sr10.jpg",
      "../Images/projects/29 shaa road/sr11.jpg",
    ],
    category: "Residential",
  },
  {
    title: "Shaa Road, Acton (Plot 2) – Matching New-Build Residential Property",
    slug: "sr27-project-2021-completion",
    description:
      "New-build residential property constructed to match adjacent development.",
    images: [
      "../Images/projects/27 Shaa Road - Acton W3/shaa.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa1.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa2.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa3.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa4.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa5.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa6.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa7.JPG",
      "../Images/projects/27 Shaa Road - Acton W3/shaa8.JPG",
    ],
    category: "Residential",
  },
  {
    title: "Bastion House, Hackney – Boutique Luxury Apartment Development (9 Units)",
    slug: "hackney-project-2020-completion",
    description:
      "Boutique new-build development of 9 high-specification luxury apartments in a contemporary architectural style. The project included demolition of existing structures, substructure works, RC Frame and traditional brick construction, Interiors featured bespoke joinery, underfloor heating, smart home wiring, and luxury fittings throughout. Communal and private outdoor spaces were also included.",
    images: [
      "../Images/projects/Hackney Project/hackney.JPG",
      "../Images/projects/Hackney Project/hackney1.JPG",
      "../Images/projects/Hackney Project/hackney2.JPG",
      "../Images/projects/Hackney Project/hackney3.JPG",
      "../Images/projects/Hackney Project/hackney4.JPG",
      "../Images/projects/Hackney Project/hackney5.JPG",
      "../Images/projects/Hackney Project/hackney7.JPG",
      "../Images/projects/Hackney Project/hackney8.JPG",
      "../Images/projects/Hackney Project/hackney9.JPG",
      "../Images/projects/Hackney Project/hackney10.JPG",
      "../Images/projects/Hackney Project/hackney11.JPG",
      "../Images/projects/Hackney Project/hackney12.JPG",
      "../Images/projects/Hackney Project/hackney13.JPG",
      "../Images/projects/Hackney Project/hackney14.PNG",
    ],
    category: "Residential",
  },
  {
    title: "BRISTOL Project 2024 completion - NEW BUILD - 9 APARTMENTS",
    slug: "bristol-project-2020-completion",
    description:
      "Newly completed residential development featuring 10 contemporary apartments in the Hackney district.",
    images: [
      "../Images/projects/Construction/con11.jpg",
      "../Images/projects/Construction/con1.JPG",
      "../Images/projects/Construction/con2.JPG",
      "../Images/projects/Construction/con3.JPG",
      "../Images/projects/Construction/con4.JPG",
      "../Images/projects/Construction/con5.JPG",
      "../Images/projects/Construction/con6.JPG",
      "../Images/projects/Construction/con7.JPG",
      "../Images/projects/Construction/con8.JPG",
      "../Images/projects/Construction/con9.JPG",
      "../Images/projects/Construction/con10.JPG",
      "../Images/projects/Construction/con12.jpg",
      "../Images/projects/Construction/con13.jpg",
    ],
    category: "Private Development",
  },
  {
    title: "2C Shaa Road, Acton – Contemporary Flat Refurbishment & Furnishing",
    slug: "sr2c-project-2020-completion",
    description:
      "Internal refurbishment and furnishing of a residential unit. Works included plastering, painting, bespoke cabinetry, flooring upgrades, lighting installations, and full furniture fit out. The project was delivered to a high contemporary standard, ready for immediate occupancy",
    images: [
      "../Images/projects/2c shaa road/2c11.png",
      "../Images/projects/2c shaa road/2c.jpg",
      "../Images/projects/2c shaa road/2c2.jpg",
      "../Images/projects/2c shaa road/2c3.jpg",
      "../Images/projects/2c shaa road/2c4.jpg",
      "../Images/projects/2c shaa road/2c7.jpg",
      "../Images/projects/2c shaa road/2c8.jpg",
      "../Images/projects/2c shaa road/2c9.jpg",
      "../Images/projects/2c shaa road/2c10.jpg",
      "../Images/projects/2c shaa road/2c1.jpg",
      "../Images/projects/2c shaa road/2c.jpg",
    ],
    category: "Private Development",
  },
  {
    title: "Charles Street, Mayfair – Grade II Listed Townhouse Refurbishment with Indoor Pool",
    slug: "charles-project-2024-completion",
    description:
      "Full internal refurbishment of a Grade II listed luxury townhouse in the heart of Mayfair. The project involved complete strip-out of the existing interior, sympathetic structural alterations in line with conservation requirements, and full MEP (mechanical, electrical, and plumbing) upgrade to modern standards while preserving listed features. Works included installation of a bespoke indoor swimming pool in the basement, creation of a lightwell in the rear courtyard to enhance natural light, and incorporation of high-end finishes such as marble bathrooms, custom hardwood joinery, underfloor heating, and advanced lighting systems. Coordination with listed building control officers and heritage consultants was integral throughout the project",
    images: [
      "../Images/projects/Chalrles Street - London Mayfar/cs.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs1.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs2.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs3.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs4.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs5.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs6.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs7.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs8.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs9.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs10.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs11.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs12.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs13.jpg",
      "../Images/projects/Chalrles Street - London Mayfar/cs14.jpg",
    ],
    category: "Residential",
  },
];

export default Projects;
